services:
  viaseguraapi:
    build:
      context: .
      dockerfile: Backend/viaseguraapi/Dockerfile
    container_name: viaseguraapi
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://viaseguradb:5432/viasegura
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - GOOGLE_CLIENT_ID=client_id
      - GOOGLE_CLIENT_SECRET=client_secret
      - JWT_SECRET=my-secret
      - JWT_EXPIRE=3600000
      - SPRING_PROFILES_ACTIVE=default
      - TZ=America/Sao_Paulo
    depends_on:
      - viaseguradb
    networks:
      - viasegura-network

  viaseguradb:
    image: postgres:16.3
    container_name: viaseguradb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=viasegura
      - TZ=America/Sao_Paulo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - viasegura-network

  pgadmin4:
    image: dpage/pgadmin4:8.9
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "15432:80"
    depends_on:
      - viaseguradb
    networks:
      - viasegura-network

volumes:
  postgres_data:

networks:
  viasegura-network:
    driver: bridge
