services:
  viaseguraapi:
    build:
      context: .
      dockerfile: Backend/viaseguraapi/Dockerfile
    container_name: viaseguraapi
    ports:
      - "8080:8080"
      - "9090:9090"
    environment:
      - DATASOURCE_URL=jdbc:postgresql://viaseguradb:5432/viasegura
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - GOOGLE_CLIENT_ID=client_id
      - GOOGLE_CLIENT_SECRET=client_secret
      - SPRING_PROFILES_ACTIVE=default
      - TZ=America/Sao_Paulo
    networks:
      - viasegura-network

volumes:
  postgres_data: